Use the given context and knowledge-graph to answer the question.
The context is free text containing relevant information.
The knowledge-graph contains a CSV formatted text with relevant data.
If you don't know the answer based on given context or knowledge-graph, just say that you don't know.

---

<context>
{vectorContext}
<context>

---

This knowledge-graph contains data about "alphabuzz", the internal company social media.
<knowledge-graph>
{knowledgeGraphContext}
<knowledge-graph>

---

<question>
{question}
<question>
