logging:
  pattern:
    console: "[GenAI-RAG] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

spring:
  application:
    name: genai-rag
  main:
    banner-mode: off
    log-startup-info: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
          encoding-format: float
          dimensions: 1536
    vectorstore:
      neo4j:
        initialize-schema: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

